servers:
  - name: ZachScott
    url: http://192.168.86.122:21025
    username: stevenmasley@gmail.com
    password: emyrk
    targets:
        - segment: 77
    websocket_channels:
        - console
        - cpu